### ISSUE TITLE
`color-alpha` dependency upgrade

### ISSUE THREAD

**Issue by archmoj** [dfcreative/color-alpha#6]
@dy Would you mind upgrading color-rgba to v3 here as well?
Thank you!

**Comment by dy** [comment]
It doesn't have color-rgba as dependency here, does it?

**Comment by archmoj** [comment]
Oh. Please upgrade `color-parse` to v2.
Thank you!

**Comment by dy** [comment]
Done

**Comment by archmoj** [comment]
Thank you very much!
:pray:
