### ISSUE TITLE
Usage in commonjs

### ISSUE THREAD

**Issue by PrettyCoffee** [dfcreative/color-alpha#7]
Hey,

I am currently creating a tailwind plugin and wanted to use this package, but when using it I encountered some errors.

It came down to this package not supporting commonjs. There seem to be a few issues:

1. The exports field in the package.json only has an "import" but no "require" entry
2. There is only an esmodule version of this package, no commonjs version.
   From my understanding, this is mainly an issue because exports and imports have a different syntax:
 
```
// esmodules
import parse from 'color-parse';

export default function alpha(...

// commonjs
const parse = require('color-parse');

module.exports = function alpha(...
```

For reproduction, you could create a file like this:
```
// script.cjs
const alpha = require('color-alpha')
console.log(alpha("white", 0.5))
```
and then run `node ./script.cjs`.

This should trigger the error I am facing.

Given you want to fix this issue, you would probably have to fix this for the dependencies as well (in this case `color-name` and `color-parse`)

If you need help with that / are open for contribution, feel free to let me know.

**Comment by dy** [comment]
Hi! Thanks for report.
Since v2 it doesn't support commonjs intentionally.
Sorry you have to face js ecosystem inconsistencies, but I think tailwind can support esm. Try replacing require with import in your tailwind config or use some bundler like esbuild in your plugin to convert to cjs.

**Comment by PrettyCoffee** [comment]
Hey, thank you for the fast answer!
I see, that makes sense to stop commonjs support.
I am already using typescript (and therefore imports) in my project for the tailwind config, so I am not sure why this is still happening.

In this case I will probably just go with a different solution.
